### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by IceflowRE** [lairdshaw/fups#1]
## CMD
`php .\fups.php -i .\settings.txt -o .\output`

## settings.txt
```
forum_type=phpBB
base_url=http://community.speed-dreams.org/
forum_ids=1
debug=1
delay=5
```

# Error
```
PHP Notice: Array to string conversion in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122

Notice: Array to string conversion in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122
PHP Notice: Undefined property: phpBBFUPS::$Array in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122

Notice: Undefined property: phpBBFUPS::$Array in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122
PHP Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\fups\classes\CFUPSBase.php:2122
Stack trace:
#0 C:\xampp\htdocs\fups\classes\CFUPSBase.php(1749): FUPSBase->write_output()
#1 C:\xampp\htdocs\fups\fups.php(157): FUPSBase->run(true)
#2 {main}
thrown in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122

Fatal error: Uncaught Error: Function name must be a string in C:\xampp\htdocs\fups\classes\CFUPSBase.php:2122
Stack trace:
#0 C:\xampp\htdocs\fups\classes\CFUPSBase.php(1749): FUPSBase->write_output()
#1 C:\xampp\htdocs\fups\fups.php(157): FUPSBase->run(true)
#2 {main}
thrown in C:\xampp\htdocs\fups\classes\CFUPSBase.php on line 2122
```

**Comment by lairdshaw** [comment]
Thanks for the report. It should be fixed now. Please let me know if you have any further problems.
