### ISSUE TITLE
Serialization of 'CurlHandle' is not allowed

### ISSUE THREAD

**Issue by malebuffy** [lairdshaw/fups#7]
Any idea why I get this error while it is scraping? For this instance it is at post 177 from 190, so don't really know why it worked for the first 177 posts

Set $serialize_filename to "D:\xampp\php\fups\optionslist.txt.serialize.txt".
PHP Fatal error:  Uncaught Exception: Serialization of 'CurlHandle' is not allowed in D:\xampp\php\fups\classes\CFUPSBase.php:393
Stack trace:
#0 D:\xampp\php\fups\classes\CFUPSBase.php(393): serialize(Object(phpBBFUPS))
#1 D:\xampp\php\fups\classes\CFUPSBase.php(1504): FUPSBase->check_do_chain()
#2 D:\xampp\php\fups\fups.php(157): FUPSBase->run(true)
#3 {main}
  thrown in D:\xampp\php\fups\classes\CFUPSBase.php on line 393

Fatal error: Uncaught Exception: Serialization of 'CurlHandle' is not allowed in D:\xampp\php\fups\classes\CFUPSBase.php:393
Stack trace:
#0 D:\xampp\php\fups\classes\CFUPSBase.php(393): serialize(Object(phpBBFUPS))
#1 D:\xampp\php\fups\classes\CFUPSBase.php(1504): FUPSBase->check_do_chain()
#2 D:\xampp\php\fups\fups.php(157): FUPSBase->run(true)
#3 {main}
  thrown in D:\xampp\php\fups\classes\CFUPSBase.php on line 393

**Comment by malebuffy** [comment]
This worked! Thanks
